from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',

    url(r'^$',
        views.DjangoDataSyncView.as_view(),
        name='django_data_sync',),

    url(r'^sync-app-model/$',
        views.SyncAppModelListView.as_view(),
        name='sync_app_model_list',),
    url(r'^sync-app-model/(?P<pk>\d+)/$',
        views.SyncAppModelDetailView.as_view(),
        name='sync_app_model_detail',),
    url(r'^sync-app-model/(?P<pk>\d+)/edit/$',
        views.SyncAppModelEditView.as_view(),
        name='sync_app_model_edit',),
    url(r'^sync-app-model/add/$',
        views.SyncAppModelCreateView.as_view(),
        name='sync_app_model_add',),
    url(r'^sync-app-model/(?P<pk>\d+)/delete/$',
        views.SyncAppModelDeleteView.as_view(),
        name='sync_app_model_delete',),
    url(r'^sync-app-model/(?P<pk>\d+)/copy/$',
        views.SyncAppModelCopyView.as_view(),
        name='sync_app_model_copy',),
    url(r'^sync-app-model/sync/$',
        views.SyncAppModelSyncView.as_view(),
        name='sync_app_model_sync',),

)


a = {u'city': u'',
 u'codename': u'agricultural-institute-centre-for-agricultural-research-hungary',
 u'comment': u'',
 u'country': {u'code': u'HU', u'name': u'Hungary'},
 u'custom_datastore_base_path': u'',
 u'custom_datastore_path': u'',
 u'custom_erp_data': {},
 u'datastore_path': u'ai-car-hungary',
 u'description': u'',
 u'django_auth_sync': False,
 u'django_group': None,
 u'erp_codename': u'openbravo',
 u'erp_entity_id': u'',
 u'full_datastore_path': u'ai-car-hungary',
 u'full_name': u'Agricultural Institute, Centre for Agricultural Research',
 u'group_entities': [],
 u'group_members': [116, 117],
 u'group_type': None,
 u'id': 107,
 u'last_edit_date': u'2016-04-21T13:05:49.189733',
 u'level': 0,
 u'name': u'Agricultural Institute, Centre for Agricultural Research',
 u'parent': None,
 u'parents_ids': [],
 u'pk': 107,
 u'properties': {},
 u'short_codename': u'ai-car-hungary',
 u'short_name': u'AI-CAR-Hungary',
 u'source_data': {},
 u'website_url': u'http://www.mgki.hu/'}